### ISSUE TITLE
attrs only works with new-style classes.

### ISSUE THREAD

**Issue by arcidodo** [praekeltfoundation/python-whatsapp-business-client#5]
`arco@av-srv:~$ sudo wabclient 
Traceback (most recent call last):
  File "/usr/local/bin/wabclient", line 11, in <module>
    load_entry_point('wabclient==2.2.1', 'console_scripts', 'wabclient')()
  File "/home/arco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/arco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/arco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/arco/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wabclient-2.2.1-py2.7.egg/wabclient/__init__.py", line 1, in <module>
    from wabclient.client import Client
  File "/usr/local/lib/python2.7/dist-packages/wabclient-2.2.1-py2.7.egg/wabclient/client.py", line 13, in <module>
    from wabclient.commands import (
  File "/usr/local/lib/python2.7/dist-packages/wabclient-2.2.1-py2.7.egg/wabclient/commands.py", line 243, in <module>
    @attr.s
  File "/usr/local/lib/python2.7/dist-packages/attrs-19.1.0-py2.7.egg/attr/_make.py", line 959, in attrs
    return wrap(maybe_cls)
  File "/usr/local/lib/python2.7/dist-packages/attrs-19.1.0-py2.7.egg/attr/_make.py", line 893, in wrap
    raise TypeError("attrs only works with new-style classes.")
TypeError: attrs only works with new-style classes.
`

**Comment by arcidodo** [comment]
changed python 2.7 to 3.6 in the bashrc file and its working now!
